<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>crm-ticketing-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CrmTicketing.Api.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CrmTicketing.Shared\CrmTicketing.Shared.csproj" />
    <ProjectReference Include="..\CrmTicketing.Domain\CrmTicketing.Domain.csproj" />
    <ProjectReference Include="..\CrmTicketing.Infrastructure\CrmTicketing.Infrastructure.csproj" />
  </ItemGroup>

</Project>
